### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kellub** [anickle060193/tabbed_tortoise_git#1]
- Make chromium the main window, if possible.
    - Add bookmark bar
- Add right click (or left-click) menu to the '+' button - One option will be select new repo, Second option will be select from recents
- Make number of recent repos configurable
- Try to make default size of window better (It's possible to open a log and have the 'Help'/'OK' buttons partially hidden. (Maybe you can send command(s) to tortoisegit to size its internal windows).

**Comment by anickle060193** [comment]
Split suggestion issue into separate issues.
