### ISSUE TITLE
Issues on startup

### ISSUE THREAD

**Issue by kellub** [anickle060193/tabbed_tortoise_git#53]
-Right clicking on new tab button doesn't show recents.
-Right clicking on tab doesn't show enabled 'Git Actions'
-Favorites aren't showing up.

**Comment by kellub** [comment]
Error log attached.
[07.53.19.295.txt](https://github.com/anickle060193/tabbed_tortoise_git/files/1052027/07.53.19.295.txt)

**Comment by anickle060193** [comment]
This was caused as a result of having installed a previous version of the application with invalid version numbering. Uninstalling and then re-installing Tabbed TortoiseGit resolved the issue.
