### ISSUE TITLE
Indicate Modified Tabs doesn't seem to do anything

### ISSUE THREAD

**Issue by kellub** [anickle060193/tabbed_tortoise_git#54]
I enabled 'Indicate Modified Tabs' and made changes to a repo, but the tab doesn't appear modified. I also tried lowering the update interval.

**Comment by anickle060193** [comment]
This was caused as a result of having installed a previous version of the application with invalid version numbering. Uninstalling and then re-installing Tabbed TortoiseGit resolved the issue.
